In [7]:
import os
import cv2
import pandas as pd

In [8]:
folder_paths = [
    "C:/Users/Administrator/Desktop/ml/female",
    "C:/Users/Administrator/Desktop/ml/male"
]

In [9]:
dataset = []

In [10]:
for i in folder_paths:
    folder_name = os.path.basename(i)
    
    # Iterate over the images in the subdirectory
    for file_name in os.listdir(i):
        image_path = os.path.join(i, file_name)
        
        if os.path.isfile(image_path):  # Only consider files
            # Load the image using OpenCV
            image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
            
            # If the image was successfully loaded
            if image is not None:
                # Resize the grayscale image to 250x250 pixels
                resized_image = cv2.resize(image, (150, 150))
                
                # Flatten the image and append each pixel as a separate feature
                flattened_image = resized_image.flatten().tolist()
                
                # Append the flattened image along with the folder name to the dataset
                dataset.append(flattened_image + [folder_name])

In [14]:

# List of folder paths containing images

# Initialize the dataset

# Iterate over the folder paths


# Convert the dataset to a pandas DataFrame
columns = [f"pixel_{i}" for i in range(150 * 150)] + ["label"]
df = pd.DataFrame(dataset, columns=columns)

# Display the first few rows of the DataFrame

,pixel_0,pixel_1,pixel_2,pixel_3,pixel_4,pixel_5,pixel_6,pixel_7,pixel_8,pixel_9,...,pixel_22491,pixel_22492,pixel_22493,pixel_22494,pixel_22495,pixel_22496,pixel_22497,pixel_22498,pixel_22499,label
0,247,247,247,247,247,247,248,248,248,248,...,227,227,228,226,225,225,225,224,145,female
1,129,132,134,139,142,143,137,131,128,127,...,168,176,171,152,191,208,205,167,172,female
2,102,102,102,102,102,102,102,102,102,102,...,103,100,98,98,98,98,99,92,65,female
3,37,37,38,39,38,40,41,41,41,42,...,29,31,27,23,24,27,29,37,34,female
4,242,242,244,244,245,245,245,246,247,247,...,253,252,253,251,251,251,250,250,250,female
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5874,231,232,232,232,232,232,232,231,231,231,...,149,148,158,155,161,151,145,145,137,male
5875,227,227,227,227,227,227,227,227,227,227,...,102,98,92,86,116,152,160,169,170,male
5876,205,205,206,206,207,206,206,208,208,208,...,40,37,36,38,41,40,43,44,46,male
5877,11,11,13,12,12,12,12,10,13,13,...,35,34,35,36,34,35,31,33,30,male
5878,147,147,147,147,147,147,149,158,158,160,...,34,37,39,38,42,40,37,37,38,male

In [13]:
df = df.sample(frac=1, random_state=42)
df

      pixel_0  pixel_1  pixel_2  pixel_3  pixel_4  pixel_5  pixel_6  pixel_7  \
0         247      247      247      247      247      247      248      248
1         129      132      134      139      142      143      137      131
2         102      102      102      102      102      102      102      102
3          37       37       38       39       38       40       41       41
4         242      242      244      244      245      245      245      246
...       ...      ...      ...      ...      ...      ...      ...      ...
5874      231      232      232      232      232      232      232      231
5875      227      227      227      227      227      227      227      227
5876      205      205      206      206      207      206      206      208
5877       11       11       13       12       12       12       12       10
5878      147      147      147      147      147      147      149      158

      pixel_8  pixel_9  ...  pixel_22491  pixel_22492  pixel_22493  \
0         248      248  ...          227          227          228
1         128      127  ...          168          176          171
2         102      102  ...          103          100           98
3          41       42  ...           29           31           27
4         247      247  ...          253          252          253
...       ...      ...  ...          ...          ...          ...
5874      231      231  ...          149          148          158
5875      227      227  ...          102           98           92
5876      208      208  ...           40           37           36
5877       13       13  ...           35           34           35
5878      158      160  ...           34           37           39

      pixel_22494  pixel_22495  pixel_22496  pixel_22497  pixel_22498  \
0             226          225          225          225          224
1             152          191          208          205          167
2              98           98           98           99           92
3              23           24           27           29           37
4             251          251          251          250          250
...           ...          ...          ...          ...          ...
5874          155          161          151          145          145
5875           86          116          152          160          169
5876           38           41           40           43           44
5877           36           34           35           31           33
5878           38           42           40           37           37

      pixel_22499   label
0             145  female
1             172  female
2              65  female
3              34  female
4             250  female
...           ...     ...
5874          137    male
5875          170    male
5876           46    male
5877           30    male
5878           38    male

[5879 rows x 22501 columns]

In [20]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
# Separate features and labels
X = df.drop(columns=['label'])  # Features
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

array([[0.96862745, 0.96862745, 0.96862745, ..., 0.88235294, 0.87843137,
        0.56862745],
       [0.50588235, 0.51764706, 0.5254902 , ..., 0.80392157, 0.65490196,
        0.6745098 ],
       [0.4       , 0.4       , 0.4       , ..., 0.38823529, 0.36078431,
        0.25490196],
       ...,
       [0.80392157, 0.80392157, 0.80784314, ..., 0.16862745, 0.17254902,
        0.18039216],
       [0.04313725, 0.04313725, 0.05098039, ..., 0.12156863, 0.12941176,
        0.11764706],
       [0.57647059, 0.57647059, 0.57647059, ..., 0.14509804, 0.14509804,
        0.14901961]])

In [19]:
from sklearn.preprocessing import LabelEncoder
y = df['label']
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)
y_encoded

array([0, 0, 0, ..., 1, 1, 1])

In [17]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_encoded, test_size=0.2, random_state=42)

In [32]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score



# Create an instance of Logistic Regression model
model = LogisticRegression(max_iter=1000)

# Start timing the training process
start_time = time.time()

# Train the model on the training data
model.fit(X_train, y_train)

# Calculate training time
training_time = time.time() - start_time
print("Training Time:", training_time, "seconds")

# Make predictions on the testing data
y_pred = model.predict(X_test)

# Evaluate the model's accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Training Time: 207.02057361602783 seconds
Accuracy: 0.9506802721088435

C:\Users\Administrator\anaconda3\anacoda\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [30]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score


# Create an SVM model
svm_model = SVC(C=1.0, kernel='rbf', gamma='scale')  # Using RBF kernel and default parameters

# Start timing the training process
start_time = time.time()

# Train the SVM model
svm_model.fit(X_train, y_train)
# Calculate training time
training_time = time.time() - start_time
print("Training Time:", training_time, "seconds")

# Make predictions on the testing data
y_pred1 = svm_model.predict(X_test)

# Evaluate the model's accuracy
accuracy1 = accuracy_score(y_test, y_pred1)
print("Accuracy:", accuracy1)

Training Time: 275.6901183128357 seconds
Accuracy: 0.9183673469387755

In [27]:
from sklearn.ensemble import RandomForestClassifier
import time


# Create a Random Forest model
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)

# Start timing the training process
start_time = time.time()

# Train the model
rf_model.fit(X_train, y_train)

# Calculate training time
training_time = time.time() - start_time
print("Training Time:", training_time, "seconds")

# Make predictions on the testing data
y_pred2 = rf_model.predict(X_test)

# Evaluate the model's accuracy
accuracy2 = accuracy_score(y_test, y_pred2)
print("Accuracy:", accuracy2)

Training Time: 62.46686577796936 seconds
Accuracy: 0.951530612244898

In [33]:
from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier(n_neighbors=5)


# Start timing the training process
start_time = time.time()

# Train the model
knn_model.fit(X_train, y_train)
# Calculate training time
training_time = time.time() - start_time
print("Training Time:", training_time, "seconds")

# Make predictions on the testing data
y_pred3 = knn_model.predict(X_test)

# Evaluate the model's accuracy
accuracy3 = accuracy_score(y_test, y_pred3)
print("Accuracy:", accuracy3)

Training Time: 0.22419261932373047 seconds
Accuracy: 0.8469387755102041